num1 = input("Enter first number: ")
num2 = input("Enter second number: ")
addtion = int(num1) + int(num2)
subtraction = int(num1) - int(num2)
multiplication = int(num1) * int(num2)
division = int(num1) / int(num2)
print(f"Addition: {addtion}")
print(f"Subtraction: {subtraction}")
print(f"Multiplication: {multiplication}")
print(f"Division: {division}")